#define CONFIG_TL_USING_BUTTON 1
#define CONFIG_TL_BUTTON_LIST_MAX 5
#define CONFIG_TL_BUTTON_SCAN_SPACE_MS 20
#define CONFIG_TL_BUTTON_DOWN_MS 100
#define CONFIG_TL_BUTTON_HOLD_MS 700
#define CONFIG_TL_BUTTON_MULTIPLE_RESET_MS 20
#define CONFIG_TL_USING_TIMER 1
#define CONFIG_TL_TIMER_LIST_MAX 5
