from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('tl_timer', src, depend = ['CONFIG_TL_USING_TIMER'], CPPPATH = CPPPATH)

Return('group')
