from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('tl_timer', src, depend = ['CONFIG_TL_USING_TIMER_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
