from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('tl_button', src, depend = ['CONFIG_TL_USING_BUTTON_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
